### ISSUE TITLE
Project stuck exporting 4414

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#289] opened 2021-04-08 09:20 UTC
reported on slack:https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1617740148087100

Project UUID: [eaefa1b6-dae1-**4414**-953b-17b0427d061e](https://contribute.data.humancellatlas.org/projects/detail?uuid=eaefa1b6-dae1-4414-953b-17b0427d061e)
Submission UUID: [8491df49-c8bb-**4499**-a04d-641fc0646a22](https://contribute.data.humancellatlas.org/submissions/detail?uuid=8491df49-c8bb-4499-a04d-641fc0646a22&project=eaefa1b6-dae1-4414-953b-17b0427d061e)

TranscriptionalHeterogeneityInLatentAndReactivatedHivInfectedCells

is still exporting after 12+ hours does it need to be re-triggered?

**Comment by rays22** [comment] 2021-04-08 15:10
The exporting of the project
* CD4_T_cells_in_brain uuid=e5d45579-1f5b-48c3-b568-320d93e7ca72
had also been stuck.

I am happy to confirm that the export of this project is now complete after the Ingest issue was resolved.

**Comment by MightyAx** [comment] 2021-04-09 08:46
Duplicate of #290?

**Comment by clairerye** [comment] 2021-04-09 08:57
sorry! Yes, not sure how I managed that

**Closed** 2021-04-22 08:45 UTC
Labels: operations
