### ISSUE TITLE
Jongeun Park: Thymus study

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#91] opened 2020-07-13 10:21 UTC
**Short name**
HumanThymicDevelopment

**Primary Wrangler:**
Marion

**Secondary Wrangler:**
Ray 

Google Drive:
https://drive.google.com/drive/folders/1-cPgACNjW4TXe9mnLQuEZE7uEHX-7aEZ?usp=sharing

**Previous ticket**
https://github.com/HumanCellAtlas/hca-data-wrangling/issues/180

**paper**
https://science.sciencemag.org/content/367/6480/eaay3224

[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=c1810dbc-16d2-45c3-b45e-3e675f88d87b)
**Key Events**

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire and move project from potential to in_progress projects
- [x] Assign the Primary Wrangler
- [ ] ~~Receive T&C form filled out by at least 1 representative of group/project~~
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [x] Fill in as much of the custom template spreadsheet filled in (https://github.com/HumanCellAtlas/hca-data-wrangling/blob/master/projects/in_progress_projects/park-thymus.md) using the pre-print to them  https://doi.org/10.1101/2020.01.28.911115 to get the additional details
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata (most likely in staging)
- [x] Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Get final approval of submission including metadata spreadsheet and data files
- [x] Submit dataset to Production and hand off tracking to data dashboard

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by mshadbolt** [comment] 2020-07-13 10:22
see the previous ticket https://github.com/HumanCellAtlas/hca-data-wrangling/issues/180 for the full back story.

I am still trying to get a full set of metadata together. I emailed more collaborators today in order to try to sort out GEX-VDJ library matching.

**Comment by mshadbolt** [comment] 2020-07-13 16:20
Received updated metadata file from JP and saved in google drive with correct matching.

He told me that he is working on submitting the SS2 data to ArrayExpress and will let me know when it is complete.

**Comment by mshadbolt** [comment] 2020-07-29 10:00
Emailed more questions to JP to get more information, the project could be submitted now but it is missing carnegie stages from 2 embryonic donors.

Will need to be exported to DCP2

**Comment by mshadbolt** [comment] 2020-08-27 09:58
@rays22 this is ready for secondary review when you have time

**Comment by rays22** [comment] 2020-08-27 19:11
* HCA metadata spreadsheet: `E-MTAB-8581.thymus_MS_v4.xlsx` passed validation by the `ingest-graph-validator`.
* The experimental design in the spreadsheet looks OK to me. I have uploaded the experimental design graph `E-MTAB-8581.thymus_MS_v4_graph.svg` to the Google drive folder of this dataset. The experimental graph is shown without any protocols to make it clearer.

Still to do:
* I have not checked the ontology terms and labels.
* I have not checked the data files.

**Comment by mshadbolt** [comment] 2020-08-28 09:00
Thanks Ray, would it be possible for you to capture how you generated the graph somewhere? I assume it is some sort of cypher query?

Is it also possible to save it in an image file that can more easily be opened? I am not sure how to open an svg file.

There is no need to check the data files.

**Comment by rays22** [comment] 2020-08-28 10:14
> Is it also possible to save it in an image file that can more easily be opened? I am not sure how to open an svg file.

You can open svg files in a web browser (Firefox, Chrome, Safari, etc.). I have considered what format to use for the image export from neo4j, and decided to use a standard vector image format (svg) as opposed to a bitmap file format. Some graphs can be quite large, like the one for this dataset, and vector images scale better when zooming in.

**Comment by rays22** [comment] 2020-08-28 16:51
### Reviewing ontology terms and labels
* There are missing ontology terms in the *'Library preparation protocol'* tab, for example:

```
library_preparation_protocol.input_nucleic_acid_molecule.ontology   library_preparation_protocol.input_nucleic_acid_molecule.ontology_label
```

I need more time to check the ontology labels for 
`cell_suspension.selected_cell_types.ontology_label`
, because I found some suspicious labels. For example, I thought *'EPCAM-positive'* cells must be epithelial cells. I am not sure if EpCAM is a leukocyte marker.

**Comment by mshadbolt** [comment] 2020-09-01 09:00
thanks ray, these are the cell types you had put in the original spreadsheet so I had assumed they were correct. I have now changed it to epithelial cells in the latest version (v5).

I also fixed the authors in the publication to follow the right format.

I also added the ontologies you mention above. let me know if you find anything else

**Comment by rays22** [comment] 2020-09-10 08:28
I have updated the selected cell type ontologies in the spreadsheet. I am going to double check the spreadsheet and upload it to Ingest UI.

**Comment by rays22** [comment] 2020-09-10 16:07
The latest spreadsheet version is `E-MTAB-8581.thymus_MS_v6.xlsx`.
What has changeged?
- [x] Line 43: changed `principal investigator  EFO:0009735` to `principal investigator  EFO:0009736` in sheet name="Project - Contributors".
- [x] Line 19: fixed spelling from `cannibis` to `cannabis` in sheet name="Donor organism".
- [x] Updated the selected cell type ontology terms in sheet "Cell suspension".

**Comment by rays22** [comment] 2020-09-10 17:42
* I have uploaded the spreadsheet `E-MTAB-8581.thymus_MS_v6.xlsx` to Ingest UI (production). It has passed metadata validation.
* I have found only 240 of the 309 fastq.gz data files listed in the spreadsheet. The 240 files are in the EBI s3 backup bucket mentioned in ticket [Jongeun Park: Thymus study for GA #180](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/180).
    * I need to find the remaining 69 data files.

**Comment by rays22** [comment] 2020-09-14 17:07
I have double checked three s3 buckets, but none of them have a complete set of 309 sequence data files listed in the metadata spreadsheet. I have found only 276 of the fastq.gz files in s3 buckets.

* Two s3 areas (old DCP1 upload area and EBI 'wrangler backup' area) are mentioned in <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/180>. The EBI `wrangler backup` area contains 276 fastq files. The other one has none.
* I have also checked the `bk-mfreeberg-park-thymus-0` data in new wrangler/contributor upload area. This area contains the same 276 fastq files as the s3 area in the previous paragraph.

The ArrayExpress (AE) ftp site appears to have a more complete set of data, except for the sample index files which are missing. For consistency with the archived data, I am going to use the submitted data files from AE. The index files are missing from the AE file set, but the sequence data appears to be demultiplexed, so I do not think it is essential to have the index files for HCA.

I have updated the metadata spreadsheet accordingly and I have uploaded it (`E-MTAB-8581.thymus_MS_v7.xlsx`) to Ingest staging.

**Comment by mshadbolt** [comment] 2020-09-15 08:08
Hi @rays22 , we should submit the files with indices for the ones we have them for. I am guessing it is the VDJ files that are missing from the s3 bucket. 

I would prefer to use the files we have in our s3 for those we have and use the arrayexpress files for the ones we don't. If we submit files without index files then they can't be processed by pipelines.

**Comment by mshadbolt** [comment] 2020-09-15 08:22
I can sort out the files if you want to move on to wrangling a new dataset

**Comment by rays22** [comment] 2020-09-15 10:03
> I can sort out the files if you want to move on to wrangling a new dataset

No, thank you. I am fine sorting out the files. I see the inconsistency of the partial pre-publication data in the s3 buckets and the peer reviewed data in the paper that have been deposited in public archives  as a problem with your suggested solution. I would like to check why the pipelines would require the sample indices for demultiplexed data before we decide how to best address the issue of missing index files.

**Comment by mshadbolt** [comment] 2020-09-15 11:33
@rays22 as secondary wrangler you don't actually have to do as much as you have done. 

Given this is a WSSS dataset and I am supposed to be handling it I would prefer to take on the completion of the dataset.

**Comment by rays22** [comment] 2020-09-15 12:00
@mshadbolt , OK, that is fine with me. Thanks.

**Comment by rays22** [comment] 2020-09-16 07:55
@mshadbolt 
FYI: You can find some of the data files that you might need in  
`data/E-MTAB-8581FASTQs`
on the wrangler EC2 instance.

**Comment by mshadbolt** [comment] 2020-12-02 17:31
decided as ray suggested to grab the files from arrayexpress instead of using existing files. All metadata and data valid and ready for export.

The other aspect of this project is SS2 data that has not been archived anywhere and have not heard from JP about wanting to archive so will reopen this in the future if we can add to this data to this project

**Comment by mshadbolt** [comment] 2021-02-03 13:57
note that matrix files can be downloaded from zenodo: https://zenodo.org/record/3711134#.YBqmyWT7Rqs
happy to do the transfer once we figure out the process for contrib matrix files

**Comment by mshadbolt** [comment] 2021-02-09 17:21
exported from ingest

**Comment by mshadbolt** [comment] 2021-02-10 11:27
@jacobwindsor the upload bucket for the files seems to be empty even though the project says it is valid, I will retrieve the files again and try again

**Comment by jacobwindsor** [comment] 2021-02-10 11:51
Thanks @mshadbolt. Let me know if it fails again and I'll look into it

**Comment by rays22** [comment] 2021-02-18 09:58
Project short name: `HumanThymicDevelopment`

**Comment by rays22** [comment] 2021-02-18 16:27
This dataset has been exported to the Terra staging area.

**Comment by lauraclarke** [comment] 2021-03-24 11:19
Needs update as defined in https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/271

**Comment by mshadbolt** [comment] 2021-04-07 08:52
@Wkt8 made this change in the ui so it is now ready for export

**Comment by mshadbolt** [comment] 2021-04-08 09:14
this was changed directly in the bucket, I have now sent the request for import.

**Comment by Wkt8** [comment] 2021-07-01 12:44
We got an email about this from a contributor saying that they had more data to submit. I'm not sure if the data is additional data, or if it is duplicate data. Need to look at the paper to be certain. 

Search for email title: Data upload thymus paper to wrangler-team@data.humancellatlas.org

**Comment by idazucchi** [comment] 2022-01-27 11:31
The contributor originally contacted us to submit more data from this publication. From a look at what is already in ingest and at the paper I think it might be SmartSeq2 mouse or human data.

The last contact was 1 July 2021. I emailed the contributor again in a new thread to ask if they still want help archiving and a few questions to assess what data they want to archive.
I am waiting for their reply to see how to move forward

**Comment by idazucchi** [comment] 2022-02-15 17:08
We have a reply from the lab!
This is potentially 10x + VDJ fastqs from 3 new pediatric donors. If they are not living (likely, all the other donors for this dataset weren't) we should be able to archive and wrangle the data.

**Comment by idazucchi** [comment] 2022-02-22 15:58
##### Living donors
The authors replied and confirmed that the donors for the missing 10x fastq files are in fact living donors, which means we are unable to archive the data for them.
I suggested that they might archive the data in EGA but even so we still would be unable to wrangle it to the DCP because of the managed access.

Can we close this ticket?

**Comment by Wkt8** [comment] 2022-02-23 09:50
Closing the ticket and we'll be notified about the SS2 data when it gets published.

**Comment by idazucchi** [comment] 2022-05-03 15:36
@Wkt8 @ESapenaVentura Can we close this ticket? the cellxgene tickets linked to this one have already been closed

**Comment by Wkt8** [comment] 2022-05-19 15:32
This needs updating 'colon' to 'thymus'
And 10x v2 to 10x v1

**Comment by Wkt8** [comment] 2022-05-20 09:05
Work out further steps on this dataset

**Comment by idazucchi** [comment] 2022-05-23 10:36
the updates needed are specified in [this email](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/YBnygHZRubI)

**Comment by Wkt8** [comment] 2022-06-09 08:23
Have spoken to Nadav and put them in contact with Anja from AE and they will update it separately.

**Comment by ESapenaVentura** [comment] 2022-07-13 09:02
Moving ticket to closed, if they come back in the future we will update this dataset

**Closed by ESapenaVentura** 2022-07-13 09:02 UTC
Labels: dataset, WSSS
