### ISSUE TITLE
GSE149689 - PBMC_Healthy/Covid19/Flu

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#97] opened 2020-07-21 16:16 UTC
**Short name**
pbmcCov19Flu

**Primary Wrangler:**
Enrique
**Secondary Wrangler:**
Ray

**Associated files:**

Google Drive: https://drive.google.com/drive/folders/1pPN9F9YGuw9bMHQBUi7wl18x53V0V_sO
*[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=95f07e6e-6a73-4e1b-a880-c83996b3aa5c&tab=upload)

**Key Events**

- [x] Fill spreadsheet (to a sufficient standard to submit dataset) 
- [x] Upload data to hca-util area (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Run graph validator
- [x] Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission including metadata spreadsheet and data files
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by ESapenaVentura** [comment] 2020-07-22 09:17
Metadata is valid: https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?id=5f180039fe9c934c8b8343ef

Data files are being uploaded. The s3 bucket has been recorded in a google doc within the folder.

@ebi-ait/hca-wranglers Anyone wants to be the secondary wrangler and review this dataset?

**Comment by ESapenaVentura** [comment] 2020-07-23 10:13
This dataset is blocked due to some (6/40) data files not being available.

Tried downloading manually those files with fasterq-dump but gives the following error for 1 of the files after 1 hour and a half:

```
2020-07-23T09:41:34 fasterq-dump.2.10.8 err: cmn_iter.c cmn_read_String( #694054913 ).VCursorCellDataDirect() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-07-23T09:41:35 fasterq-dump.2.10.8 err: cmn_iter.c cmn_read_uint8_array( #152199169 ).VCursorCellDataDirect() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-07-23T09:41:35 fasterq-dump.2.10.8 err: row #152199169 : READ.len(119) != QUALITY.len(0) (F)
2020-07-23T09:41:35 fasterq-dump.2.10.8 fatal: SIGNAL - Segmentation fault
fasterq-dump quit with error code 1
```

Which leads me to think the data files have not been replicated to the ena warehouse/made accessible directly through SRA because they are corrupt and this is a pretty new dataset.

**Comment by lauraclarke** [comment] 2020-08-04 12:09
@ESapenaVentura did you try and get the files from the NCBI or just the ENA?

https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11680226

**Comment by ESapenaVentura** [comment] 2020-08-05 09:40
@lauraclarke I always try to get the files from the ENA warehouse (easier/more consistent to parse metadata). 

For what I've seen so far, there are files who don't make it to ENA (Like the one you're pointing out), usually displaying SRR as the only viable option for download (All the others require certified aws/gc accounts)

I haven't tried with many files using fastq-dump (and derivates), but the times I've tried with this dataset fastq dump has given errors, so I'm assuming the files are somehow invalid.

Not sure if at this point we should contact SRA

**Comment by lauraclarke** [comment] 2020-08-05 10:34
Thanks, unless it seems like a uber valuable dataset it probably isn't worth it

**Comment by ESapenaVentura** [comment] 2020-08-18 06:56
it's only missing 2 out of 40 files now. I have deleted those from the spreadsheet and created a new one: 

- Spreadsheet in folder: https://drive.google.com/drive/folders/1pPN9F9YGuw9bMHQBUi7wl18x53V0V_sO (Under name with suffix _without_SRR11680208)
- UI submission: https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=ee694c49-3099-4c46-a5ec-3c5472b307f3&project=95f07e6e-6a73-4e1b-a880-c83996b3aa5c
- Tested with the ingest-graph-validator: Looks ok!

I think it's worth it to push it even if it's missing the files from a donor.

If @lauraclarke could confirm whether we should do it or not and a @ebi-ait/hca-wranglers could do the secondary wrangle, it would be awesome!

**Comment by lauraclarke** [comment] 2020-08-18 19:10
Do we know what we have lost, is it more of the same or is it something unique?

**Comment by ESapenaVentura** [comment] 2020-08-19 12:46
As stated in the operations meeting, we will proceed with this dataset and flag somehow that it's missing a donor.

Any @ebi-ait/hca-wranglers want to secondary review it?

**Comment by ESapenaVentura** [comment] 2020-08-24 08:44
I have just checked and, over the weekend, they have added the last files for the last donor, so the dataset is actually complete. I will update the spreadsheet

**Comment by ESapenaVentura** [comment] 2020-08-24 09:18
I have uploaded the spreadsheet with the full metadata under the name `GSE149689_ontologies_full_20200824.xlsx`

The last file is still uploading to the hca-util area

**Comment by rays22** [comment] 2020-08-24 10:06
Hi @ESapenaVentura,
Would you like me to do the secondary wrangling for this dataset?

**Comment by ESapenaVentura** [comment] 2020-08-24 10:08
Hi @rays22 @mshadbolt agreed to secondary review, worth chatting with her to see if she has started reviewing but if not and you both agree, happy for you to take it

**Comment by rays22** [comment] 2020-08-24 18:58
- Spreadsheet version `GSE149689_ontologies_full_20200824.xlsx` passed all the validation tests by the `ingest-graph-validator`.
- I have created an experimental design graph of `GSE149689_ontologies_full_20200824.xlsx` using the `ingest-graph-validator`. It looks all right to me:
    <https://drive.google.com/file/d/1a0QAwVy_qQ4nPCkktthxdcLd9E-4oDTn/view?usp=sharing>
- I can confirm that the correct ontologies have been used in the metadata spreadsheet.

- I have **not** checked the data files.
- I have **not** checked the Ingest UI submission:

```
Aug 18, 2020, 7:20:30 AM    ee694c49-3099-4c46-a5ec-3c5472b307f3    Draft
```

**Comment by ESapenaVentura** [comment] 2020-08-25 08:12
Hi @rays22 thanks for the review.

I am going to proceed without the donor as I am not able to retrieve the R2 file by any means. 

The spreadsheet is the same, just without the biomaterials/files associated to the run SRR11680208

I'll start uploading files now.

**Comment by ESapenaVentura** [comment] 2020-09-02 09:42
Leaving the ticket open as we have a missing donor.

Once we have the ability to update, we should look back into this dataset.

**Comment by ESapenaVentura** [comment] 2021-04-09 07:20
This ticket is no longer blocked as in the last sprint @Wkt8 was able to download the last 3 files from the last donor.

**Comment by Wkt8** [comment] 2021-04-21 15:18
When making the update please see this ticket! https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/260 Also make the change to project.project_core.project_description.

**Comment by ESapenaVentura** [comment] 2022-01-27 16:39
Done with the update 

I also added analysis files

Will need further updates on the library preparation protocols (Outdated labels)

**Comment by ami-day** [comment] 2022-03-03 15:21
This dataset is suitable for SCEA. @ESapenaVentura I think you submitted this to HCA DCP last release in January? is this the latest version: https://docs.google.com/spreadsheets/d/1zgoOn7fdNt2niSTiLt97vz4NdSMTCvdd/edit#gid=1827791073 or a different google sheet is? I will do the pre-conversion via the hca2scea tool and upload the output files to the dataset folder.

**Comment by ESapenaVentura** [comment] 2022-03-03 16:25
@ami-day it's a mix of this https://docs.google.com/spreadsheets/d/1C6zoBjmkyGbXV8RUR5l1FML_qzZs_GCL/edit?usp=sharing&ouid=105945877951113459382&rtpof=true&sd=true

and this https://docs.google.com/spreadsheets/d/1zTuYivT6k7-2C_zhXl6WJ_1sjblzjqJm/edit?usp=sharing&ouid=105945877951113459382&rtpof=true&sd=true

one of the donors was not available at the time of the original submission, so it had to be added afterwards in a new submission

**Comment by ami-day** [comment] 2022-03-04 13:33
Assigned E-HCAD-id: E-HCAD-44

**Comment by ami-day** [comment] 2022-03-07 11:31
Manually curated the files. Have uploaded them to Gitlab, merge request is here: https://gitlab.ebi.ac.uk/ebi-gene-expression/scxa-metadata/-/merge_requests/292

Note: E-HCAD has changed to **E-HCAD-45**

**Comment by rachadele** [comment] 2023-10-23 16:42
i am working on it, there were 2 misnamed files in the staging area but i think i figured out how to fix it

**Comment by rachadele** [comment] 2023-10-24 17:23
someone deleted the submission with the updates, so now we will need to start from scratch unfortunately

**Comment by idazucchi** [comment] 2023-10-25 16:07
I've added manually the missing donor and analysis files to the first submission to avoid export issues with multiple submissions.
Exported data & metadata + filled import form

**Comment by idazucchi** [comment] 2023-11-16 12:37
The new donor made it to the broswer! I'm checking if we can drop the matrix that was added to the project prior to the analysis schema so we don't have a duplicate of GSE149689_matrix.mtx.gz

**Comment by idazucchi** [comment] 2023-12-21 08:29
#### Removing duplicate file from Data Portal
The same file was decribed twice:
1. GSE149689_matrix.mtx.gz  was originally added to the project as a supplementary file as the [MVP implementation](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_system_design.rst#511describing-cgms-as-supplementary-files) --> so matrix file + supplemenatry file metadata + descriptor + links.json
2. GSE149689_matrix.mtx.gz  was added as a part of the update as an analysis file

**Solution**
After some discussion on slack (see [here](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1701108889471639) and [here](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1703002691192699)) we've agreed with Nate that the best solution to remove the extra files that come with point 1 is to soft delete and re-import the whole project. All the uuids will remain the same so it will be a small change for the users

I'm filling out the import form and requesting the soft deletion
- [ ] check project in Data Portal

**Comment by idazucchi** [comment] 2024-01-16 20:35
the proposed solution could impact the DCP generated matrices generated for this project - this issue is discussed [here](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/1226) along with a similar case, so I'll remove the ticket from the operations board

**Comment by idazucchi** [comment] 2024-04-17 11:29
issue resolved

**Closed by idazucchi** 2024-04-17 11:29 UTC
Labels: dataset, audr, broker to:SCEA, Release 14, Helped by Dev, Release 33
