### ISSUE TITLE
GSE137720_GSE136103_Single-Cell Transcriptomics Uncovers Zonation of Function in the Mesenchyme during Liver Fibrosis

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#535] opened 2021-10-25 15:02 UTC
### Secondary Wrangler:
@ESapenaVentura 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1A_R52KVUp8ctpSRdCTqAz_-fWCyRnIrP

### Published study links

* Paper: https://doi.org/10.1016/j.celrep.2019.10.024 

* Accessioned data: GSE137720

**Ingest**
https://contribute.data.humancellatlas.org/projects/detail?uuid=d71c76d3-3670-4774-a9cf-034249d37c60

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment] 2021-11-09 16:35
I filled out almost all the spreadsheet fields I can at this time and I run fill_ontology.py 

##### Problems
1. Ontology term for Liver fibrosis
Is the liver fibrosis the same as cirrhosis? If yes there already is an otology term available, if not there is no suitable ontology term.

2. GEO accession represent multiple sample - donor untraceable
Rather than having one GEO accession per donor or sample, the authors chose to group together under the same accession all the samples that underwent the same treatment.
This means that currently there is no way to track the biomaterial donor. It is possible that the same donor donated more than one sample, but this information is not available at the moment.
3. SmartSeq2 data - donor untraceable
More than one sample were processed in the same plate. A layout of the samples in the plate is available. However there is no way of linking the output of a specific well to an accession run or file. This means that it is not possible to track the biomaterial flow


#### Next steps

1. I want to find out the difference between liver fibrosis and liver cirrhosis. If they are two different things I will have to look for an ontology term for liver fibrosis. Potentially differentiating between acute and chronic liver fibrosis. 

2-3. I wrote to the authors asking for the missing information (Oct 28th) but until they reply with the missing information this will be stalled

**Comment by idazucchi** [comment] 2021-11-10 15:10
**Ontology term for Liver fibrosis**
From this [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC546435/)

> Liver fibrosis is the excessive accumulation of extracellular matrix proteins including collagen that occurs in most types of chronic liver diseases. Advanced liver fibrosis results in cirrhosis, liver failure, and portal hypertension and often requires liver transplantation.

From this I think we can conclude that _liver fibrosis needs a separate ontology term_ from liver cirrhosis. There are two possible ways to include liver fibrosis in the HCAO:

1.  Importing a term from EFO

**Comment by ipediez** [comment] 2021-11-11 10:01
@idazucchi to discuss with @Wkt8 and @ESapenaVentura on slack channel

**Comment by idazucchi** [comment] 2021-11-12 13:17
**Ontology term for Liver fibrosis - in MONDO**
Enrique pointed out that the only ontologies admitted by the [schema](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/ontology/disease_ontology.json) in the known disease field are MONDO and PATO.
Since the aim of requesting the liver fibrosis term is modelling the animal disease model, the only viable option is the first one.

I will open a ticket for the ontology term request shortly.

Discussion of phenotype field as part of the metadata?

**Comment by ESapenaVentura** [comment] 2021-11-15 10:08
There's more discussion needed around the term - Need Wranglers to meet about it

**Comment by idazucchi** [comment] 2021-11-16 15:43
**Update - MONDO Ontology term for Liver fibrosis**
It is not possible to import a human phenotype directly in the MONDO HCAO subset.
Paola Roncaglia suggested to request a new term in MONDO called 'hepatic fibrosis (disease)' to distinguish it from the HP phenotype term. 
She opened a [new term request ticket](https://github.com/monarch-initiative/mondo/issues/4000) in the MONDO repo on our behalf.
**Timeframe** 
MONDO editors aim to include the NTR in the next release which will be at the beginning of December. Hopefully that will leave enough time for the term to be imported in HCAO in the December release as well

**Comment by ESapenaVentura** [comment] 2021-11-16 16:03
@idazucchi this means that this dataset won't make it for release 12 (Dec 6th). Is it ok if I delete the milestone from the ticket?

**Comment by idazucchi** [comment] 2021-11-17 09:21
Yes, the release 12 milestone makes no sense for this dataset

**Comment by idazucchi** [comment] 2021-11-17 09:56
**Selected cells**
In this study there are two selections protocols, one states clearly the cells selected, hepatic stellate cells, while the other doesn't.  So for some cell suspensions the information is missing

**Organ part**
The whole liver is extracted and processed but throughout the paper the authors refer to the mesenchymal liver cells as the population under study. 
From what I understand mesenchyme is a developmental term, whereas stroma is more of a functional term, but they point to the same thing. Mesenchyme gives rise to the mesoderm, which in turn generates the connective tissues, so the stroma of the liver.
This is why I put down liver stroma as organ part

**Authors**
I emailed them again on November 16th. Until they reply I cannot go forward.

**Comment by idazucchi** [comment] 2021-11-29 11:30
**Plate well ID**
The plate well ID was present in the filenames given by the authors, but this information has gone missing because SRA renamed the files according to the SRRun accession. 
The data access tab reports the original name, so the plate well ID can be recovered, and along with that the donor mouse can be recovered as well.

**Comment by idazucchi** [comment] 2021-12-03 17:39
### Donor tracing
The study used 27 mice: 

- 12 analysed with SmartSeq2: the samples' well layout is reported in GEO. The submitted fastq file name include the well label. 
> I am using this information to associate the fastq, SRRun accession, well label to the right donor.

- 15 analysed with 10x: the mice were grouped in threes, had the same treatment applied, and then analysed together in the same lane. For each set of three mice there are 4+ fastqs that have three donors. 
> I have to fill out the input cell suspension ID

**Comment by idazucchi** [comment] 2021-12-08 14:35
All cell suspension and file tabs are complete.
**SmartSeq2 control wells**
The authors confirmed by email that these wells do not include cells, unfortunately the email didn't have the wrangler-team in CC.
I am excluding the control wells from the dataset since they do not include cells.

**Comment by idazucchi** [comment] 2021-12-08 19:30
I attempted to retrieve the fastq but I haven't found an effective method to fetch them based on their SRR, which is crucial for this dataset, as there are 1562 SRR and no way to select, due to the fact that not all the SRR of one SRX are needed

**Comment by aaclan-ebi** [comment] 2021-12-13 09:57
@idazucchi need to put the data in Ingest. Need help in downloading a subset of files.

**Comment by idazucchi** [comment] 2021-12-16 11:36
Files and spreadsheet are in ingest, validation is blocked by the missing ontology term, which should be released in the next few days

**Comment by idazucchi** [comment] 2021-12-17 16:47
The ontology term `Fibrotic liver disease` has been released to HCAO, I updated the spreadsheet and proceeded with the graph validation.
The error `smartseq2_has_2-3_files` was raised because there is just one fastq file per SmartSeq2 plate well. However this error should't be raised because the sequencing was single ended so there is only one R1 file. 
I discussed it with Enrique and opened a [ticket](https://github.com/ebi-ait/ingest-graph-validator/issues/62) to address this.

Once this is resolved the dataset should be ready for secondary review

**Comment by ofanobilbao** [comment] 2022-01-13 08:03
@ESapenaVentura will secondary review

**Comment by ESapenaVentura** [comment] 2022-01-13 13:53
For the review, the dataset looks pretty good! I have a couple of suggestions:

## Donor organism
-I’d take out the SRX accession from there, it doesn’t fit that process 

## Specimen from organism
-There are dissociation protocols associated with the collection protocol for some mice (“perfusion_dissociation_protocol”). Are these dissociation protocols or should be collection protocols?
-I’d also take the SRX accessions from here


## Library preparation
-Missing ontology term for PCR (cDNA amplification method)


I have a small comment, though. For what it seems, it looks like the experiment contains multiplexed (more than 1 donor per set of fastq files). I don't think the pipelines can take this kind of data (The 10x ones), so we may need to discuss it with the other teams

Also I couldn't find the analysis files/protocols, are they missing for any reason?

**Comment by Wkt8** [comment] 2022-01-14 09:59
To discuss the issue of multiplexed 10X fastq files going to the DCP with the UCSC folks.

**Comment by idazucchi** [comment] 2022-01-17 09:09
Regarding the multiplexed 10x data Parisa advised to submit the data because it is still relevant to the community. We need to bring this up with the pipelines team so that they know not to process it

**Comment by ESapenaVentura** [comment] 2022-01-17 15:46
Just a couple more comments! after fixing these, it should be fine:

## Analysis protocols
- To separate the computational methods and derivation processes, you don’t need to add a space in between the terms; this will be picked up as part of the string (e.g. “alignment “)
- I noticed that for the matrix cell counts, they’re associated with the “_layout.csv.gz” files, but those files are identified as “molecular property identifier”. Is it meant to be like that or are the cell counts supposed to be associated with the “_counts.tab.gz” files?

## Analysis file
- As we discussed, if you could change the ontology to use [Feature table](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_1270) it would be great!

**Comment by gabsie** [comment] 2022-01-18 10:04
This should be ready to go, but it's affected by the linking of submission problem.

**Closed** 2022-03-11 11:55 UTC
Labels: dataset
