### ISSUE TITLE
CrossTissueSARS-COV-2Study - Lungmap

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#693] opened 2022-03-11 11:36 UTC
### Project short name:
CrossTissueSARS-COV-2Study

### Primary Wrangler:
Ami

### Secondary Wrangler:
Ida

### Associated files

* Google Drive: 

https://drive.google.com/drive/folders/1zxWX3174cW95hDi2QdKscUDp_vJUDuz2

https://docs.google.com/spreadsheets/d/1Umn7edCleECLB79MFhUvK9BQYWzAP16p6CtDk8cYu6E/edit#gid=981242441

### Published study links
This is a reanalysis paper! The newly published datasets have been confirmed by the authors [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/EZjDQXzJHx8/m/QfFol6E9HQAJ)

* Paper: https://www.nature.com/articles/s41591-020-01227-z
* Accessioned data: 
- http://broad.io/hcacovid19
- https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE153643 - differs from the data availablity section, but was indicated by the author, see email thread above
- https://singlecell.broadinstitute.org/single_cell/study/SCP1292
- https://app.terra.bio/#workspaces/kco-incubator/COVID-19_cross_tissue_analysis/

**Ingest**
[project](https://contribute.data.humancellatlas.org/projects/detail?uuid=a27dd619-25ad-46a0-ae0c-5c4940a1139b)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment] 2022-03-11 11:54
This may be a lattice dataset, waiting on them to answer a message

**Comment by prabh-t** [comment] 2022-03-14 09:56
Enrique confirmed this is not lattice dataset.

**Comment by ipediez** [comment] 2022-04-11 14:23
@ipediez to check if this dataset is elegible

**Comment by ami-day** [comment] 2022-05-12 11:48
Moving this to stalled. I started curating it, but it is unclear which data was newly generated and where the link to the data is in the single cell portal.

**Comment by idazucchi** [comment] 2022-05-18 14:52
Hi Ami! 
I'm done with the secondary review. The part that can be wrangled is actually really small so this should hopefully make it for release 17!
I have a couple of comments, in particularl I would model differently the pooled tissues

### Project
- cell count: do we want to include the number quoted in the abstract or do we want a count that reflects the newly sequenced cells?
> We performed a meta-analysis of 31 lung single-cell RNA-sequencing studies with 1,320,896 cells from 377 nasal, airway and lung parenchyma samples from 228 individuals
- I’m not sure the project is an official HCA publication, they don’t have the acknowledgement sentence in the publication
- the grant list is partial: CZI, Knut and Alice Wallenberg Foundation, European (Horizon2020, ERC) funding are absent

### Donor
- I would model 3 adipose donors and 4 liver donors, using the same metadata for all since no information is available
- I think that the adipose donors were alive at the moment of collection because the tissue comes from abdominoplasty surgery

### Specimen
- I would model this with one specimen per donor, 3 for the adipose tissue and 4 for the liver
- the collection protocol id doesn’t match either of the protocols

### Cell suspension
- I would model this as two cell suspensions, one adipose and one liver, with the respective specimens pooled together
- the sample ids could be moved from the specimen to the pooled cell suspensions

### Analysis protocol
- `computational methods` should contain the software used in the analysis, I think this information is absent in this case 

### Analysis file
- please list the individual files so that they can be described more accurately
- in the single cell portal there are UMAOP files available, it would be good to include them as well. The other files available there might overlap with those from GEO, I’m not sure if they should be included anyway

**Comment by ami-day** [comment] 2022-05-18 16:28
5d163161-f829-4473-889b-680c7cb0756e

**Comment by ami-day** [comment] 2022-05-18 16:47
graph validating

**Comment by ami-day** [comment] 2022-05-18 16:48
Submitted.

**Comment by ami-day** [comment] 2022-05-18 17:16
Exported.

**Comment by ami-day** [comment] 2022-05-18 17:17
Submitted form.

**Comment by idazucchi** [comment] 2022-06-16 11:21
This needs a major update: 
It was unclear which datasets were already published and which ones were generated for this study, but from the [single cell portal](https://singlecell.broadinstitute.org/single_cell?type=study&page=1&terms=https://www.biorxiv.org/content/10.1101/2020.04.19.049254v1&scpbr=hca-covid-19-integrated-analysis) it looks like a large number was published with this paper for the first time. It might be best to confirm which ones with the authors.

Minor updates needed:
- [ ] supplementary links are not formatted correctly in the broser
- [ ] publication link goes to data availability
- [ ] linking issues:
   - [ ] process `process_id_9` is not linked to `liver_sample_4`
   - [ ] the analysis file processes should have one cell suspension each as input

**Comment by ami-day** [comment] 2022-06-16 16:10
Now graph validating

**Comment by ami-day** [comment] 2022-06-16 16:25
Update exported and import form submitted.

**Comment by ami-day** [comment] 2022-07-15 16:12
Looks ok in the Data Browser apart from "There are no accessions for this project.". There is a GEO and NCBI SRA study accession in the project metadata that should be displayed.

**Comment by ami-day** [comment] 2022-07-18 10:25
Looks good to me.

**Closed** 2022-07-22 08:49 UTC
Labels: dataset, managed access, hca pub, Release 16, Release 17, Release 18
