### ISSUE TITLE
Archive HumanHematopoieticProfiling data in ENA

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#17] opened 2020-05-14 11:24 UTC
This study has current BioStudies and BioSamples accessions:
- BioStudies: [S-SUBS8](https://www.ebi.ac.uk/biostudies/studies/S-SUBS8)

The most up to date spreadsheet is here:
https://drive.google.com/open?id=1wWza_Ww4NewLtrmZ8UFUPRqCSdo-ULvR&authuser=mshadbolt@ebi.ac.uk&usp=drive_fs

It has a linked AUDR ticket here:
https://github.com/HumanCellAtlas/hca-data-wrangling/issues/354

Relevant updates should have been made in the latest spreadsheet as it was part of the r-release. I am not sure if updated metadata was used for the archiving process (@ESapenaVentura ?)

The data is in the DCP DSS

I am not sure if data files were already converted to BAM as part of the original attempt to archive. (@ESapenaVentura ?)

See this issue for previous work https://github.com/HumanCellAtlas/hca-data-wrangling/issues/427

**Comment by ESapenaVentura** [comment] 2020-05-14 12:18
For archiving, I used the metadata spreadsheet that we had for the r-release, so unless changes were made afterwards, it should be the latest metadata!

**Comment by rays22** [comment] 2020-06-26 15:11
### Updating spreadsheet to include BioStudies and Biosamples accessions

I am updating the latest metadata spreadsheet
`release-PeerHumanHaematopoieticProfiling-hca_spreadsheet-2020-03-05_uuid.xlsx`
to include the BioStudies and BioSamples accessions.
This version of the spreadsheet contains entity UUIDs and it seems that the UUID columns in the spreadsheet causes the ingest-graph-validator to fail finding cross-entity relationships (in other words, it fails to create any edges in the graph).
The `0 edges` error by the ingest-graph-validator is consistent with what I see in Ingest submission:
* Ingest project <https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=091cf39b-01bc-42e5-9437-f419a66c8a45>

*  There are 0 processes shown by Ingest for the following submission:
`Mar 5, 2020, 2:39:10 PM a843b006-722b-4ee5-a200-2f9389e0ecf4    Complete`

which I believe is a submitted version of the spreadsheet
`release-PeerHumanHaematopoieticProfiling-hca_spreadsheet-2020-03-05_uuid.xlsx`.
I can not be sure as they are independent and potentially different versions of the same data object that are (hopefully) manually synchronised.

The upload area
`s3://org-hca-data-archive-upload-prod/a843b006-722b-4ee5-a200-2f9389e0ecf4/`
is empty. This is consistent with Ingest showing 0 data files for the above (`a843b006...`) submission.

Also, I can not access the data files in Ingest for an earlier submission from the same project:
`s3://org-humancellatlas-upload-prod/7dbcf5ae-f8d7-487c-a3d4-794d8639a1e2/`.

When I try to `hca upload list` after selecting the `7dbcf5ae...` area, I get errors that include `Upload Area Not Found`.

In any case, I will upload the updated spreadsheet that includes the existing archive accessions to Ingest, validate it, and transfer (s3 to s3) the data files if necessary for ENA archiving.

**Comment by rays22** [comment] 2020-06-26 17:56
I have added the following archive accessions to the latest HCA spreadsheet:
```
UUID_type	UUID	archive accession
project.uuid	091cf39b-01bc-42e5-9437-f419a66c8a45	S-SUBS8
donor_organism.uuid	219098db-6a8d-4e5c-9cd9-8cfcac665a4c	SAMEA6877934
donor_organism.uuid	e24f10c2-e21d-44c4-9450-46029c443941	SAMEA6877923
donor_organism.uuid	39d1a24f-1785-476d-9c04-065be917e3ff	SAMEA6877924
specimen_from_organism.uuid	dde588fc-dcb4-4bc1-bc4e-badbce058fa7	SAMEA6877925
specimen_from_organism.uuid	20156407-a6f8-447e-a21e-dbbf66a58043	SAMEA6877937
specimen_from_organism.uuid	92254a9e-3a14-4760-b229-d914f3e8973f	SAMEA6877927
cell_line.uuid	3b602421-8101-426f-990a-9e0eee51d483	SAMEA6877921
cell_line.uuid	501ba65c-0b04-430d-9aad-917935ee3c3c	SAMEA6877932
cell_line.uuid	4ccd163e-a630-4ede-bc0c-336ba044b783	SAMEA6877928
cell_suspension.uuid	91cbade9-dece-49f8-b922-c34a82694e69	SAMEA6877922
cell_suspension.uuid	533707fc-bf44-4b2b-8231-9cdc8f820ae0	SAMEA6877920
cell_suspension.uuid	dfae7c13-5b3f-42f7-b85a-dd99882022af	SAMEA6877931
cell_suspension.uuid	7eab5bec-1f2f-4c0a-bb00-f40b92f3bdb5	SAMEA6877936
cell_suspension.uuid	907ccd95-51af-4a95-b641-9f364730c127	SAMEA6877926
cell_suspension.uuid	cf818dda-9e22-437a-bf1c-4ce8110b89eb	SAMEA6877929
cell_suspension.uuid	13eab62e-0038-4997-aeab-aa3192cc090e	SAMEA6877930
cell_suspension.uuid	423cc632-0de2-42fd-a502-e07161878906	SAMEA6877935
cell_suspension.uuid	a91fc069-49e6-4666-8923-6085041abd44	SAMEA6877933
```

**Comment by rays22** [comment] 2020-06-28 14:02
### 2020-06-28 Notes

* I have uploaded HCA spreadsheet `PeerHumanHaematopoieticProfiling-hca_spreadsheet-2020-06-26_accessions.xlsx` updated with BioStudies and BioSamples archive accessions to Ingest. The spreadsheet has passed cross-entity validation by <https://github.com/ebi-ait/ingest-graph-validator/tree/master/graph_test_set>. This version of the spreadsheet does not contain the UUID columns of a previous version, because those columns cause validation to fail.
* I have uploaded the validated HCA spreadsheet updated with archive accessions to <https://drive.google.com/drive/u/0/folders/1XCnIjhxzcJuwtPUcRYisxtQQn-W0-ljT>.
* I have downloaded the fastq.gz data files of project `Profiling of CD34+ cells from human bone marrow to understand hematopoiesis` from the HCA Data Storage System (DSS) to EC2 `ip-172-31-71-222`.
* I have uploaded the data files to the upload area that belongs to submission `b8a76a08-c9e9-4c30-9bef-43cbb3b51287` in [Ingest](https://ui.ingest.archive.data.humancellatlas.org).
* Submission [b8a76a08-c9e9-4c30-9bef-43cbb3b51287](https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=b8a76a08-c9e9-4c30-9bef-43cbb3b51287&project=091cf39b-01bc-42e5-9437-f419a66c8a45)
has passed validation by Ingest.

**********************

- [ ] Before moving forward I need to confirm with other wranglers that the UUIDs that I did not include in this submission would not be required for ENA archiving.

**Comment by rays22** [comment] 2020-06-29 17:44
I am blocked at updating this dataset in Ingest UI with BioStudies and Biosamples accessions.
1. I need up-to-date instructions to do the metadata-update which work in the current Ingest UI with this specific dataset that comes from DCP1 and already has updates.
    - I am unable to download the spreadsheet from Ingest for any of the two current submissions in <https://ui.ingest.archive.data.humancellatlas.org/>. Nothing happens if I click the `Download spreadsheet button`. At this step I was trying to follow the 'Updating Metadata through Spreadsheets' process <https://github.com/HumanCellAtlas/ingest-central/wiki/Updating-Metadata-through-Spreadsheets>.
    - I have not received any response or confirmation on Slack to my query if it is OK for me to use a spreadsheet with UUID columns `release-PeerHumanHaematopoieticProfiling-hca_spreadsheet-2020-03-05_uuid.xlsx` that I downloaded from <https://drive.google.com/drive/u/0/folders/1XCnIjhxzcJuwtPUcRYisxtQQn-W0-ljT> instead of a freshly downloaded copy from Ingest UI.
2. I also need to know how to associate the data files that I have already uploaded to 
`s3://org-hca-data-archive-upload-prod/b8a76a08-c9e9-4c30-9bef-43cbb3b51287/` with any new metadata-update submission.

**Comment by rays22** [comment] 2020-06-30 11:27
I have not proceeded to `Submit to Project` the update submission in Ingest UI:

    Jun 29, 2020, 1:49:36 PM	3c60caab-b045-4ad8-b6c5-d2bc4f1c085a	Valid	

However, I have downloaded the latest spreadsheet after my update from Ingest UI and uploaded it to
<https://drive.google.com/drive/u/0/folders/1XCnIjhxzcJuwtPUcRYisxtQQn-W0-ljT>
as
`HumanHematopoieticProfiling-3c60caab-b045-4ad8-b6c5-d2bc4f1c085a.xlsx`.

**Comment by rdgoite** [comment] 2020-07-06 15:08
I've submitted the Project exported to DCP/1 to DSP for archiving. See the status in this link for more information: https://submission.ebi.ac.uk/api/submissions/d29e26c7-b212-45d8-92ce-1747769c85b0

**Comment by aaclan-ebi** [comment] 2020-07-08 15:26
Seems like the files aren't uploaded to DSP yet:

```
{
	"errors": {
		"https://submission.ebi.ac.uk/api/assayData/23b39b92-5e16-4584-9e06-d0189aebf0a2": [{
			"FileReference": [
				"The file [5d30e4f09be88c0008a9b286.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/60945f32-627b-443d-80b2-d27e7c393635": [{
			"FileReference": [
				"The file [5d30e4da9be88c0008a9b284_8.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/6ca6512b-c0c7-4031-a1a1-643333c18d8e": [{
			"FileReference": [
				"The file [5d30e4d29be88c0008a9b281.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/7c1a7ce7-0a09-4e72-a99b-6b87054925b5": [{
			"FileReference": [
				"The file [5d30e4f09be88c0008a9b287.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/871a965b-3f1a-4636-a699-80a3c13e6eb2": [{
			"FileReference": [
				"The file [5d30e4cf9be88c0008a9b27f.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/8dda9ab4-e67e-493e-aa7c-14322c9c0d99": [{
			"FileReference": [
				"The file [5d30e4db9be88c0008a9b285_7.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/8f1ba947-5356-41cb-8784-70fd5409266f": [{
			"FileReference": [
				"The file [5d30e4d29be88c0008a9b282.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/933cf504-11ba-41b3-8ab0-629db23433f3": [{
			"FileReference": [
				"The file [5d30e4db9be88c0008a9b285_3.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/a23f22d5-8be7-44b0-963f-05ce39356398": [{
			"FileReference": [
				"The file [5d30e4da9be88c0008a9b283_4.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/b05cecee-c2ec-48bb-8de2-f3fd779c6e6e": [{
			"FileReference": [
				"The file [5d30e4da9be88c0008a9b284_6.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/e2d560f4-e1ab-4340-ae85-29166ff63ffd": [{
			"FileReference": [
				"The file [5d30e4da9be88c0008a9b283_7.bam] referenced in the metadata is not exists on the file storage area."
			]
		}],
		"https://submission.ebi.ac.uk/api/assayData/f13609bf-fe43-487b-8b34-6723e98f8e7a": [{
			"FileReference": [
				"The file [5d30e4cf9be88c0008a9b280.bam] referenced in the metadata is not exists on the file storage area."
			]
		}]
	},
	"pending": []
}
```

**Comment by rays22** [comment] 2020-07-08 15:50
> Seems like the files aren't uploaded to DSP yet

@aaclan-ebi : Is the archiver uploading the data files from
`s3://org-hca-data-archive-upload-prod/b8a76a08-c9e9-4c30-9bef-43cbb3b51287/` ? I am asking it, because I have made update submissions to this project and each submission appeared to have different s3 upload areas shown in Ingest UI.
Or, is it just a case of slow file upload speed?

**Comment by aaclan-ebi** [comment] 2020-07-08 17:23
Since this dataset has already been submitted to DSS. The files should be automatically downloaded from DSS when File Archiver is ran. There's no extra step needed to upload or download the files again.

**Comment by aaclan-ebi** [comment] 2020-07-09 12:54
@rdgoite did you get a chance to run the file archiver for this? Just want to make sure we're not triggering duplicate jobs.

**Comment by rdgoite** [comment] 2020-07-09 12:57
I didn't run file archiver for this because my understanding was that we didn't need to as this was already exported to DCP/1.

**Comment by aaclan-ebi** [comment] 2020-07-10 09:06
We do need to submit the data files to DSP to submit to ENA and get sequencing run accessions.

No worries, we'll just continue the DSP submission. Thanks for confirming.

**Comment by aaclan-ebi** [comment] 2020-07-10 13:23
File archiver job is now ongoing.

**Comment by aaclan-ebi** [comment] 2020-07-14 11:27
The job encountered an error:

```
Starting Downloading 2 files from dcp for manifest 5d30e4cf9be88c0008a9b280
Bundle Version Command: hca dss get-bundle --uuid bc9c33e9-e576-4450-b9e4-fc257df43396 --replica aws
Bundle Version Error: Error: Command failed: hca dss get-bundle --uuid bc9c33e9-e576-4450-b9e4-fc257df43396 --replica aws
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/usr/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/dist/src/util/bundle-downloader.js:43:44
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
``` 
i tried downloading the bundle manually which was successful. I can't replicate the issue so I reran the job and it's proceeding with that bundle now. Will keep on monitoring this.

**Comment by aaclan-ebi** [comment] 2020-07-16 08:29
9 / 12 sequencing runs were already uploaded.

**Comment by aaclan-ebi** [comment] 2020-07-16 14:13
12/12 sequencing runs were uploaded. But 3 recently uploaded files have pending validation and cluster is busy. https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1594897129002500

**Comment by aaclan-ebi** [comment] 2020-07-17 11:15
All file validation has completed. I submitted the DSP submission however it seems that there were processing errors. Will clarify with DSP team.

```
{
  "_embedded" : {
    "processingStatuses" : [ {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:38.930+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352032",
      "alias" : "HCA_sequencingRun_93f77490-944f-4b6b-af41-a6fdfe8e312b",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/8cbb7897-70e2-494d-8430-4b8ad6ef7afe"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/8cbb7897-70e2-494d-8430-4b8ad6ef7afe{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/8cbb7897-70e2-494d-8430-4b8ad6ef7afe/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.099+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352039",
      "alias" : "HCA_sequencingRun_dd101e2f-39d2-4dff-97df-f539f8f43bbc_8",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/38511386-6b29-4d87-9440-20067a9a6684"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/38511386-6b29-4d87-9440-20067a9a6684{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/38511386-6b29-4d87-9440-20067a9a6684/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.010+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352035",
      "alias" : "HCA_sequencingRun_ef07fc4a-c48f-4c3b-ab5e-cc0ba7beaecb",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/aa685931-1ab1-4969-8f11-332d8f68aedb"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/aa685931-1ab1-4969-8f11-332d8f68aedb{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/aa685931-1ab1-4969-8f11-332d8f68aedb/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:38.909+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352031",
      "alias" : "HCA_sequencingRun_e70725f5-0fc0-4938-a464-44da5e06692e",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/1cd7f46e-24c6-4f76-a551-8494f3c58d1b"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/1cd7f46e-24c6-4f76-a551-8494f3c58d1b{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/1cd7f46e-24c6-4f76-a551-8494f3c58d1b/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.060+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352037",
      "alias" : "HCA_sequencingRun_f59c9106-16a8-47f8-b681-490d23ee09de",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/9d044c1c-08da-422b-8cd8-0eea2d75a92e"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/9d044c1c-08da-422b-8cd8-0eea2d75a92e{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/9d044c1c-08da-422b-8cd8-0eea2d75a92e/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.174+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352042",
      "alias" : "HCA_sequencingRun_33cfc718-5cfa-49d1-b854-caa92fdb67ff_7",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/1c79c2ee-e026-4b67-b2cd-51fadc37510d"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/1c79c2ee-e026-4b67-b2cd-51fadc37510d{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/1c79c2ee-e026-4b67-b2cd-51fadc37510d/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:38.965+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352033",
      "alias" : "HCA_sequencingRun_8a107656-f9fd-48ee-aae7-ee1bb4d7a254",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/3ab8d668-1f51-42bc-98e2-cc5dbf3de47f"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/3ab8d668-1f51-42bc-98e2-cc5dbf3de47f{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/3ab8d668-1f51-42bc-98e2-cc5dbf3de47f/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:38.980+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352034",
      "alias" : "HCA_sequencingRun_33cfc718-5cfa-49d1-b854-caa92fdb67ff_3",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/83ae754b-3261-4f8c-b08e-5f7690a390c2"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/83ae754b-3261-4f8c-b08e-5f7690a390c2{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/83ae754b-3261-4f8c-b08e-5f7690a390c2/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.159+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352041",
      "alias" : "HCA_sequencingRun_dea208e8-fc47-4ba0-aecf-f06236318548_4",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/5eb46a84-eb76-4995-a71e-27c2852a5225"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/5eb46a84-eb76-4995-a71e-27c2852a5225{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/5eb46a84-eb76-4995-a71e-27c2852a5225/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.130+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352040",
      "alias" : "HCA_sequencingRun_dd101e2f-39d2-4dff-97df-f539f8f43bbc_6",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/be7c4d52-d0c1-44f4-a869-3ff01c3a4a19"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/be7c4d52-d0c1-44f4-a869-3ff01c3a4a19{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/be7c4d52-d0c1-44f4-a869-3ff01c3a4a19/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.081+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352038",
      "alias" : "HCA_sequencingRun_dea208e8-fc47-4ba0-aecf-f06236318548_7",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/e3ed8f78-7b88-4e9f-99f5-51686a523b63"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/e3ed8f78-7b88-4e9f-99f5-51686a523b63{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/e3ed8f78-7b88-4e9f-99f5-51686a523b63/dataType"
        }
      }
    }, {
      "archive" : "Ena",
      "status" : "Error",
      "lastModifiedDate" : "2020-07-17T11:08:39.027+0000",
      "lastModifiedBy" : "Ena",
      "accession" : "ERR4352036",
      "alias" : "HCA_sequencingRun_a00bce9d-8c46-41d7-86cc-c06a3123cc59",
      "submittableType" : "AssayData",
      "_links" : {
        "self" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/ff8bd253-9546-4a4c-9b33-5bfe9bbc1e0c"
        },
        "processingStatus" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/ff8bd253-9546-4a4c-9b33-5bfe9bbc1e0c{?projection}",
          "templated" : true
        },
        "dataType" : {
          "href" : "https://submission.ebi.ac.uk/api/processingStatuses/ff8bd253-9546-4a4c-9b33-5bfe9bbc1e0c/dataType"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "https://submission.ebi.ac.uk/api/processingStatuses/search/findBySubmissionId?submissionId=d29e26c7-b212-45d8-92ce-1747769c85b0&page=0&size=20"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 12,
    "totalPages" : 1,
    "number" : 0
  }
}
```

**Comment by aaclan-ebi** [comment] 2020-07-21 11:10
Karoy and Haseeb from DSP team confirmed that the sequencing runs are submitted successfully to ENA. It's just that some internal errors happened in DSP. There's no further actions needed for us. 

I am not sure of the next steps yet for the Ingest submissions. There are cases that i think requires design or special handling in Ingest. 

1. How to export DCP datasets which have updates (new accessions) ? Some of those new accessions were already stored in Ingest. Some are not.

2. New datasets which were archived prior the archiver support for storing accessions in Ingest. Those have accessions but the accessions may not have been put back to Ingest yet.

**Comment by lauraclarke** [comment] 2020-07-21 15:13
@aaclan-ebi does https://github.com/ebi-ait/hca-ebi-dev-team/issues/226#issuecomment-661920039

apply to this dataset too?

**Comment by aaclan-ebi** [comment] 2020-07-21 15:14
Yes, i'll include that!

**Comment by ESapenaVentura** [comment] 2020-09-02 09:18
The outstanding issues with this are addressed in a more specific ticket.

I will close this ticket for now but feel free to reopen if necessary.

**Comment by lauraclarke** [comment] 2020-11-04 15:15
This ticket is being reopened as we need to ensure EMBL-EBI archive accessions are added back to the ingest records for this project so they can eventually be updated in the DCP

**Comment by mshadbolt** [comment] 2020-12-22 15:42
The publication can also be updated from the bioarxiv to: https://www.nature.com/articles/s41587-019-0068-4

**Comment by idazucchi** [comment] 2022-02-09 16:08
### Needs clarification
- [ ] Parisa the primary wrangler - is it UCSC?
- [ ] project and publication titles don't match 
- [ ] all files raised an error
- [ ] are there biosample accessions --> submission 7dbcf5ae-f8d7-487c-a3d4-794d8639a1e2 but disappeared with submission a843b006-722b-4ee5-a200-2f9389e0ecf4
- [x] are there EMBL-EBI archive accessions  --> submission 7dbcf5ae-f8d7-487c-a3d4-794d8639a1e2

**Comment by idazucchi** [comment] 2022-02-11 11:24
This update was already done
I checked with Wei both from ingest and the GCS staging area: all the the accessions are already present.

I'm moving the ticket to finished

**Closed** 2022-03-28 09:49 UTC
Labels: dataset, broker to:EBIArch, DCP1.0, Release 14
