### ISSUE TITLE
`ingest-graph-validator __version__ = "0.6.1"` fails to hydrate datasets from xls and ingest

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#215] opened 2020-12-22 20:26 UTC
### Description of the problem
I have updated the local installation of the `ebi-ait/ingest-graph-validator` to version `__version__ = "0.6.1"`, but I can run the metadata validation tests, because the `ingest-graph-validator` fails to load (`hydrate`) datasets.

1. `git pull` to update local copy.
2. Re-installed `ebi-ait/ingest-graph-validator` in a new virtual environment from github:

```
    git clone git@github.com:ebi-ait/ingest-graph-validator.git
    cd ingest-graph-validator
    python3 -m venv venv
    source ./venv/bin/activate
    pip install .
```

3. I have also tried to install it from PyPI into a new virtual environment.

``` 
    python3 -m venv venv
    activate
    pip install ingest-graph-validator
``` 

All three installations of the `ingest-graph-validator` fail when I try to
either `hydrate xls`
or `hydrate ingest` with errors similar to the following:

>
[connectionpool.py:662 -              urlopen() ] 2020-12-XX XX:XX:XX,XXX - urllib3.connectionpool - WARNING - Retrying (Retry(total=XX, connect=None, read=10, redirect=None, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at XXXXXXXXXXXXXX>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /

* * * *
### Acceptance criteria
- [x] any bugs fixed
- [x] fixed version of the `ingest-graph-validator` is tested to confirm that it works properly on both Linux and OS X operating systems

**Comment by rays22** [comment] 2021-01-05 15:53
If I export the current ingest api uri as an environmental variable
```
export INGEST_GRAPH_VALIDATOR_INGEST_API_URL="https://api.ingest.archive.data.humancellatlas.org"
```

and try to `hydrate` a spreadsheet, 
then I get this error:

>    f'There was an error retrieving the schema information to process the spreadsheet. {str(e)}')
ingest.importer.importer.SchemaRetrievalError: There was an error retrieving the schema information to process the spreadsheet. Was unable to read the property migrations file from URL https://schema.dev.data.humancellatlas.org/property_migrations

**Comment by lauraclarke** [comment] 2021-01-05 15:59
@rays22 you might have been caught out while @aaclan-ebi is making changes to different version of the schema server. I don't know where it gets that URL from but I think it now has to be https://schema.data.humancellatlas.org/property_migrations

**Comment by rays22** [comment] 2021-01-05 17:06
> @rays22 you might have been caught out while @aaclan-ebi is making changes to different version of the schema server. I don't know where it gets that URL from but I think it now has to be https://schema.humancellatlas.org/property_migrations

Yes, I suspect that too. I have not found any hard coded reference to the schema url in the ingest-graph-validator code base and config file, but it is apparently a dependency somewhere.

**Comment by aaclan-ebi** [comment] 2021-01-06 13:18
Yes, that is correct @rays22 . The issue is in the hca-ingest (or ingest-client) python module which is a dependency in ingest-graph-validator.  I've released a new version of hca-ingest yesterday. The schema url issue should be fixed in the latest version. I'll just upgrade the version in ingest-graph-validator and do some testing.

**Comment by aaclan-ebi** [comment] 2021-01-06 14:00
@rays22 i got a fix in this branch task/update-hca-ingest , could you try testing it by checking out this branch? should follow the same steps. But you should `git checkout  task/update-hca-ingest` before `pip install .` . Many thanks!

**Comment by rays22** [comment] 2021-01-06 17:07
I did some tests, and the issue has been fixed in branch `task/update-hca-ingest`. 
Thanks @aaclan-ebi !

**Closed** 2021-01-13 11:08 UTC
Labels: bug, operations
