### ISSUE TITLE
Investigate issue with GSE118184KidneyOrganoid

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#417] opened 2021-08-27 08:56 UTC
**submission**: https://contribute.data.humancellatlas.org/submissions/detail?uuid=68102d9a-0e91-4ba8-bb27-070bdba3c606&project=16ed4ad8-7319-46b2-8859-6fe1c1d73a82

**Issue**: Organoid genus species "unspecified"

**Context**: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1630016648010200

**Comment by Wkt8** [comment] 2021-09-01 08:54
Have followed up with a slack message: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1630486450020300?thread_ts=1630016648.010200&cid=C9XD6L0AD

**Comment by ESapenaVentura** [comment] 2021-09-14 10:56
Any news on this?

**Comment by Wkt8** [comment] 2021-09-14 13:07
It appears to be an issue with subgraph structure, and how the indexer obtains the genus_species information. It seems that the indexer obtains "genus_species" from donor_organism.genus_species, and the subgraphs in this project do not have donor_organisms. 

Additionally, in our schema we have multiple 'genus_species' in order to be agnostic. Hannes has an idea on how to amend the metadata-schema to solve this issue which involves removing all the 'genus_species' apart from that in donor_organism and adding donor_organism to other subgraphs. He will file a ticket on the metadata-schema repo to be prioritised.

**Comment by ofanobilbao** [comment] 2021-10-15 11:15
I believe this Organoid dataset has the same issues as the others on this ticket so I have added the ticket compiling all the issues as a blocker for this one as well. If I have not understood correctly, please, feel free to remove the dependency.

**Comment by ofanobilbao** [comment] 2022-05-18 14:00
@Wkt8 I believe this was one of the datasets you wrangled. From what I can see in the DCP portal, the issue is resolved, so I am closing this ticket. Please, reopen if I did not get that right. 😊

**Closed as completed by ofanobilbao** 2022-05-18 14:00 UTC
Labels: operations, blocked: schema changes
