### ISSUE TITLE
Fix BAM to FASTQ - 20a871b4-5684-4630-96bd-146f94debf1c

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#519] opened 2021-10-21 09:33 UTC

**Comment by jacobwindsor** [comment] 2021-11-10 11:49
- Project is https://contribute.data.humancellatlas.org/projects/detail?uuid=ad98d3cd-26fb-4ee3-99c9-8a2ab085e737
- [ENA project](https://www.ebi.ac.uk/ena/browser/view/PRJEB39602?show=reads)
- [List of sequencing runs to be supressed]([https://app.zenhub.com/files/261790554/85f09db2-b214-4eb4-a2fb-d5b2c0aef4b1/download](https://app.zenhub.com/files/261790554/85f09db2-b214-4eb4-a2fb-d5b2c0aef4b1/download))
- [Full ENA report]([https://app.zenhub.com/files/261790554/edda74a3-76bf-4cbe-80ea-e34b5d1eb06f/download](https://app.zenhub.com/files/261790554/edda74a3-76bf-4cbe-80ea-e34b5d1eb06f/download))

**Comment by jacobwindsor** [comment] 2021-11-10 12:25
Download to `/nfs/production/hca/20a871b4-5684-4630-96bd-146f94debf1c`

**Comment by jacobwindsor** [comment] 2021-11-10 12:27
I haven't performed step 8 in the [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/update_ena_runs_SOP.html#steps) yet since I haven't been able to get the script to function

**Comment by ipediez** [comment] 2021-11-11 09:51
This is in process

**Comment by jacobwindsor** [comment] 2021-11-12 10:31
Uploading to ENA. See `screen -r 188486` for progress

**Comment by ofanobilbao** [comment] 2021-11-17 11:13
@jacobwindsor is this finished?

**Comment by jacobwindsor** [comment] 2021-11-17 11:27
This has been uploaded to `20a871b4-5684-4630-96bd-146f94debf1c` on the Webin FTP server. 

Step 8 and step 12 need to be ran

**Comment by jacobwindsor** [comment] 2021-11-17 11:35
These are now uploaded to the Webin FTP server in folder20a871b4-5684-4630-96bd-146f94debf1c. However, the Webin FTP server was being a bit unreliable at the time of uploading so they *might* fail checksumming.

Step 8 and step 12 in the SOP need doing

**Comment by ke4** [comment] 2021-11-19 18:08
Step 8 has been done. Working on step 12. I have some issues, but trying to solve them as I am going along.

**Comment by ke4** [comment] 2021-11-23 10:25
I tried to submit the files yesterday, but the script failed with errors. When I checked the receipt XML from ENA it shows that the files are not exists in the upload area.
I checked ENA's FTP and there is no folder with the submission uuid.
I am not sure what happened.  I need to upload them again.

**Comment by ke4** [comment] 2021-11-23 11:02
I started to upload the files to ENA FTP and waiting for them to be uploaded.

**Comment by ke4** [comment] 2021-11-24 10:24
I checked and all the 768 files are on the ENA FTP server under the `/20a871b4-5684-4630-96bd-146f94debf1c` folder.

**Comment by jacobwindsor** [comment] 2021-11-25 09:59
@ke4 has found that this is a possible duplicate of another project as FASTQs already in ENA

**Comment by ke4** [comment] 2021-11-25 10:45
I checked in Ingest and the `Cells of the adult human heart` project has only got 1 submission: uuid:`20a871b4-5684-4630-96bd-146f94debf1c`, title: `Submission - HeartSingleCellsAndNucleiSeq` and its files are already fixed in ENA. So we can move this ticket to done. It was a duplicated ticket, but not duplicate submission. :-)

**Closed** 2021-12-02 09:15 UTC
Labels: operations
