### ISSUE TITLE
AdultLungElo - A spatial multi-omics atlas of the human lung reveals a novel immune cell survival niche

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#236] opened 2021-01-27 15:16 UTC
**Primary Wrangler:**
Wei Kheng Teh

**Secondary Wrangler:**

**Associated files:**

Paper: https://www.biorxiv.org/content/10.1101/2021.11.26.470108v1

Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=957261f7-2bd6-4358-a6ed-24ee080d5cfc

Google Drive: https://drive.google.com/drive/folders/1Ty3xrV-MEcjCDklpUHSC1Yna7pcvv699
Google Sheet: https://docs.google.com/spreadsheets/d/1skxc1GJovUgfn4Ugbm3zZiuzvOugEA0H/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true

**Key Events**

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Final Steps:**
- [ ] secondary review
- [ ] export to HCA (after checking with Elo for publicity date)
- [ ] archiving of Visium to ArrayExpress
- [ ] archiving of data files and metadata via DSP to ENA

**Comment by Wkt8** [comment] 2021-02-12 09:27
Had a meeting with contributors Elo and Peng together with @ESapenaVentura - Notes and Email sent out to the contributors here in this google doc: https://docs.google.com/document/d/1wJIjR55kWyGbcZ3FOK8BMOMCKkSMD6oMfcgYLt68mtA/edit

**Comment by Wkt8** [comment] 2021-03-18 13:35
This is actually the ticket for the AdultLungElo project. This includes CBTM adult lung samples.

**Comment by Wkt8** [comment] 2021-07-05 10:57
This is at a point where we are waiting for additional Visium metadata and for Elo to send a final annotated cell matrice.

**Comment by prabh-t** [comment] 2022-03-14 10:07
Wei requires help to archive this dataset.

**Comment by Wkt8** [comment] 2022-03-17 09:45
Needs:
- secondary review
- export to HCA (after checking with Elo for publicity date)
- archiving of Visium to ArrayExpress
- archiving of data files and metadata via DSP to ENA

**Comment by MightyAx** [comment] 2022-03-17 09:57
@ami-day to secondary review.

**Comment by Wkt8** [comment] 2022-03-17 11:31
Ami has secondary reviewed and given me feedback.

**Comment by gabsie** [comment] 2022-03-22 09:55
no publication date yet. might be private for now.

**Comment by idazucchi** [comment] 2022-03-24 10:13
Elo confirmed that the data can be published

**Comment by Wkt8** [comment] 2022-03-25 09:41
https://contribute.data.humancellatlas.org/submissions/detail?uuid=9e880501-55f3-442d-9908-efae1dac9be9&project=957261f7-2bd6-4358-a6ed-24ee080d5cfc

**Comment by ipediez** [comment] 2022-03-25 09:41
Stuck on metadata validating since yesterday, @prabh-t to help Wei to unstuck this, probably related to yesterday's problems with projects stuck

**Comment by Wkt8** [comment] 2022-03-25 09:47
Prabhat says it's just a size issue - so will keep waiting on it.

**Comment by Wkt8** [comment] 2022-03-25 14:46
Exported. Now needs archiving.

**Comment by Wkt8** [comment] 2022-03-31 08:38
I am following this SOP: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/archiving_SOP.html#step-2-of-3---archiving-files-to-dsp

DSP archiving is stalled, I have created a DSP submission with the ingest submission UUID with a POST request (30th March, 2pm), but I receive 'null' when attempting to retrieve the DSP submission UUID via the ingest submission UUID.

**Comment by ofanobilbao** [comment] 2022-03-31 08:55
@ke4 to try and help on this

**Comment by Wkt8** [comment] 2022-04-13 10:06
Update required for export to the DCP that the curator is unspecified. Need to think about how this will work with the deleted processes!

**Comment by aaclan-ebi** [comment] 2022-04-13 16:12
The metadata entities of this project were updated with accessions. They also need to be submitted to DCP.

**Comment by ESapenaVentura** [comment] 2022-04-14 09:01
👀 duty

**Comment by ofanobilbao** [comment] 2022-04-27 12:20
@Wkt8 if I understand you've already pushed this to DCP and archived it and now you're waiting for data to be in ENA and then update the DCP submission with the accessions. Correct?

**Comment by idazucchi** [comment] 2022-05-31 11:21
needs minor update 
- to change 10x labels and 
- visium bulk cell? 
- add wei as curator
- add cell count estimate
- accession not showing up?

**Comment by Wkt8** [comment] 2022-07-08 09:44
@amnonkhen or @MightyAx could you please set this dataset state from 'Archived' to 'Metadata Valid' so that I could edit and update it? Updates are not permitted in the 'Archived' metadata state.

**Comment by amnonkhen** [comment] 2022-07-14 12:07
@Wkt8 it is done.

**Comment by ke4** [comment] 2022-07-20 14:05
Done it with curl request and rollout deployment of ingest-state-tracking. It looks OK now and the submission is in `Metadata Valid` status.

**Comment by Wkt8** [comment] 2022-07-21 14:01
Update made, import form submitted, moving to done

**Comment by Wkt8** [comment] 2022-07-22 08:50
In the exported state.

**Comment by Wkt8** [comment] 2022-09-22 09:58
Meeting with Amanda to discuss as some analysis files need to be updated - see here: https://docs.google.com/document/d/1a5rjrLw3Al2EEWAqewkV-aZbmge0qERR0vQSd2i_VvY/edit

**Comment by Wkt8** [comment] 2022-09-29 09:57
Spreadsheet updated and available here: 
https://docs.google.com/spreadsheets/d/1skxc1GJovUgfn4Ugbm3zZiuzvOugEA0H/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true

Remaining actions
- [ ] Put new files into a hca-util upload area
- [ ] Delete staging area 
- [ ] Check Nathan has deleted the terra staging area
- [ ] Wait until the 'deleting submissions and adding new submissions' fix has been put into production
- [ ] Delete existing submission from https://contribute.data.humancellatlas.org/projects/detail?uuid=957261f7-2bd6-4358-a6ed-24ee080d5cfc
- [ ] Submit new submission 
- [ ] Export project
- [ ] Submit export form
- [ ] Notify downstream components
- [ ] Notify Amanda Oliver (ao15@sanger.ac.uk)
- [ ] Submit files to cellxgene

**Comment by idazucchi** [comment] 2022-10-06 08:52
some files are stuck in validation --> ops [ticket](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/932)

**Comment by Wkt8** [comment] 2022-10-10 15:35
Exporting!

**Comment by idazucchi** [comment] 2022-10-18 16:28
@Wkt8 this is marked as release 21 in the manifest, can you change it to release 22?

**Comment by Wkt8** [comment] 2022-10-19 12:56
yeah we need to change it oops

**Comment by Wkt8** [comment] 2022-11-15 13:52
Verified on catalog dcp = 22. All good.

**Comment by Wkt8** [comment] 2023-01-17 16:04
Making another update for publication links

**Comment by Wkt8** [comment] 2023-01-18 17:07
now in graph validating

**Comment by Wkt8** [comment] 2023-01-18 17:29
- [ ] Exported
- [ ] Submitted product import form

**Comment by idazucchi** [comment] 2023-02-27 19:32
verified in the data browser

**Comment by ofanobilbao** [comment] 2023-06-29 07:48
I can't see a reason for this Dataset to be open again and in Stalled. So I will close it. Does not seem to have any comments saying something is wrong with it.

**Comment by arschat** [comment] 2024-02-20 10:32
Contributor [asked](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/0kLzfQ-hWQo/m/1ZRvUyoIAAAJ) to add the processed spaceranger output files both in HCA & in ArrayExpress.
They have provided the files [here](https://drive.google.com/drive/folders/1CFmmgHVKtDCa0I7eyPZQ28Qm4qblbyX8).

I've opened a ticket in ArrayExpress helpdesk to re-open the the submission, and I will update in HCA for the next release 36.

**Comment by arschat** [comment] 2024-02-22 18:26
- Uploaded the files through hca-util (upload area: `79e143e8-9e91-4afb-aa23-ac7ee7be46ae/`) and sync designated to "Upload Area Location"
- Updated new files though api but also previous files to upgrade to analysis_file 7.0.0 from 6.5.0.
- Graph validated & hit export @ 18:26
    <details>
    <summary>Code for updating files through API</summary>
    
    > from hca_ingest.api.ingestapi import IngestApi
    > 
    > api = IngestApi(url="https://api.ingest.archive.data.humancellatlas.org/")
    > headers_json = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token}
    > api.set_token(f"bearer {token}")
    > 
    > query = [{
    >         "field": "content.describedBy",
    >         "operator": "IS",
    >         "value": "https://schema.humancellatlas.org/type/file/6.5.0/analysis_file"
    >     },
    >     {
    >         "field": "project.id",
    >         "operator": "IS",
    >         "value": "61a7c1dcc7b79307bb4863b7"
    >     }
    > ]
    > 
    > json = {"content": {"describedBy": 'https://schema.humancellatlas.org/type/file/7.0.0/analysis_file'}}
    > analysis_files = api.post('https://api.ingest.archive.data.humancellatlas.org/files/query?operator=AND', json=query).json()
    > for old_file in analysis_files['_embedded']['files']:
    >     json = {'content': old_file['content']}
    >     json['content']['describedBy'] = 'https://schema.humancellatlas.org/type/file/7.0.0/analysis_file'
    >     response = api.patch(old_file['_links']['self']['href'], headers=headers_json, json=json)
    > 
    > 
    > query = [{
    >         "field": "content",
    >         "operator": "IS",
    >         "value": None
    >     },
    >     {
    >         "field": "project.id",
    >         "operator": "IS",
    >         "value": "61a7c1dcc7b79307bb4863b7"
    >     }
    > ]
    > 
    > 
    > files_list = api.post('https://api.ingest.archive.data.humancellatlas.org/files/query?operator=AND', json=query).json()
    > 
    > for file in files_list['_embedded']['files']:
    >     json = {"content": {
    >         "describedBy": "https://schema.humancellatlas.org/type/file/7.0.0/analysis_file",
    >         "schema_type": "file",
    >         "file_core": {
    >           "file_name": file['fileName'],
    >           "format": "zip",
    >           "content_description": [
    >               {
    >                   "text": "gene expression matrix",
    >                   "ontology": "data:3112",
    >                   "ontology_label": "gene expression matrix"
    >               }
    >           ],
    >           "file_source": "Contributor"
    >         },
    >         "genome_assembly_version": "GRCh38"
    >       }
    >     }
    >     response = api.patch(file['_links']['self']['href'], headers=headers_json, json=json)
    >     if response.ok:
    >         print(file['_links']['self']['href'])
    >     else:
    >         print("ERROR HERE " + file['_links']['self']['href'])
    >         print(response.status_code)
    >         break

    </details>

**Comment by arschat** [comment] 2024-03-12 11:40
AE opened the experiment for edits, and files were uploaded & assigned to samples. I added the peer-reviewed publication, too.
As per Silvie's guidelines, I re-submitted the experiment.
Once 
- [ ] the AE submission is processed without errors, and
- [ ] the HCA submission is verified in the browser
I will close this ticket.

**Comment by arschat** [comment] 2024-04-02 16:12
Verified in browser. Waiting for AE submission to be live before closing.

**Comment by arschat** [comment] 2024-04-22 09:24
Problem in AE submission, needs re-upload of fastq files as well as the processed. Shared Silvie's guidelines with Krzysztof, and wait for them to upload.

**Comment by arschat** [comment] 2024-05-03 09:11
Upload of data files completed. Project was validated and re-submitted and waiting for re-validation to complete update.

**Comment by arschat** [comment] 2024-05-03 12:21
AE submission is now public. Update has been completed. Closing ticket.

**Closed by arschat** 2024-05-03 12:21 UTC
Labels: dataset, WSSS, broker to:ArExp, Imaging, Release 15, Release 19, Release 22, Helped by Dev, Release 24, Release 36
