### ISSUE TITLE
Fix BAM to FASTQ -  90513d30-5f47-473e-b180-c37a974fc03b

### ISSUE THREAD

**Issue by ke4** [ebi-ait/hca-ebi-wrangler-central#682] opened 2022-03-07 16:12 UTC
SOP: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/update_ena_runs_SOP.html
ENA project: https://www.ebi.ac.uk/ena/browser/view/PRJEB36885?show=reads

**Events:**
1. AdultHemOrgans project has 2 "datasets"/"submissions" that were archived
2. Submission 1 was archived - bam files were submitted
3. Submission 2 was archived - bam files were submitted (192 fastq = 64 bam files)
4. There were issues in the bam files. We want to replace them with the fastq files.
5. Submission 1 was re-archived - to replace the bam files with the fastq files, we ask for the suppression of bam files
"rearchived":
--- delete/"suppress" the old sequencing runs containing the bam files
--- create new sequencing runs containing the fastq files
6. All the bam files for 2 submissions were also suppressed.
7. Submission 2 files are now not available and we found out the sequencing experiment to sequencing run grouping is incorrect
--- create new sequencing experiments - 32 sequencing experiment 
--- create new sequencing runs containing the fastq files - 192 fastq files

**Problem:**
The previous sequencing runs were suppressed (in ENA). The sequencing experiments to sequencing runs linking were incorrect.

**Tasks:**
1. Submit the seq experiments. Make sure to point to correct sample accessions.
2. Submit new seq runs - use SOP

**Comment by ke4** [comment] 2022-03-08 11:19
The list of BAM files to suppress already has been sent to ENA when we worked on this ticket: Fix BAM to FASTQ - cb156730-90b0-4b77-944c-bfc263204c61

**Comment by ke4** [comment] 2022-03-08 11:39
Step 9 (Started) - Copy from Terra from this location: `broad-dsp-monster-hca-prod-ebi-storage/prod/455b46e6-d8ea-4611-861e-de720a562ada/data` has started into EBI cluster into `/nfs/production/hca/90513d30-5f47-473e-b180-c37a974fc03b` folder.

**Comment by prabh-t** [comment] 2022-03-14 09:53
Alegria working on this.

**Comment by aaclan-ebi** [comment] 2022-03-14 10:36
It looks like the files for this submission([90513d30-5f47-473e-b180-c37a974fc03b](https://contribute.data.humancellatlas.org/submissions/detail?uuid=90513d30-5f47-473e-b180-c37a974fc03b&project=455b46e6-d8ea-4611-861e-de720a562ada)) were already downloaded to the `ls /nfs/production/hca/cb156730-90b0-4b77-944c-bfc263204c61/` .

**Comment by ESapenaVentura** [comment] 2022-03-15 11:32
Had a meeting with Alegria, we are going to re-prioritise this. 

Needs several actions:
- [ ] Determine the correct linking
- [ ] Delete the experiments associated with this submission
- [ ] Re-submit with the proper experiments/sampels/runs linking

**Comment by aaclan-ebi** [comment] 2022-03-18 10:17
It looks like all bam files are all suppressed so I'm setting this ticket high priority now because the bam files we need to replace are no longer showing in the ENA browser.

Enrique already confirmed that the linking should be correct in Ingest. We need to re-archive this submission such that only sequencing experiments will be submitted via DSP and use the direct ENA route to submit new sequencing runs and fastq files.

**Comment by idazucchi** [comment] 2022-03-24 10:06
@aaclan-ebi will set up a meeting with @ESapenaVentura @amnonkhen  @prabh-t  to discuss how to archive the submission

**Comment by ipediez** [comment] 2022-03-25 09:59
@ke4 @aaclan-ebi  @ESapenaVentura and @prabh-t to have a meeting today

**Comment by jacobwindsor** [comment] 2022-03-28 08:42
@prabh-t and @aaclan-ebi to pair

**Comment by aaclan-ebi** [comment] 2022-03-28 16:41
Started working with @prabh-t on this. The specific steps are listed in https://docs.google.com/document/d/1xtw6kJPbcB1gDnszfZn_QFc-lCd8qnxHdbzPA-n8eQQ/edit

**Comment by ke4** [comment] 2022-03-29 08:46
@ke4 to check if he still got the md5 values for the files

**Comment by ipediez** [comment] 2022-03-30 09:06
@prabh-t working on this, thanks!

**Comment by ofanobilbao** [comment] 2022-03-31 08:47
@aaclan-ebi and @prabh-t kept pairing on this yesterday. They experienced slowness. Maybe due to validation happening redundantly. @aaclan-ebi is going to create another ticket

**Comment by aaclan-ebi** [comment] 2022-04-06 15:19
Marking this ticket as also externally blocked because of issue in DSP connection with AAP API.

**Comment by aaclan-ebi** [comment] 2022-04-11 11:49
The AAP issue is now fixed, will work on this after the AdultLungElo archiving ebi-ait/hca-ebi-wrangler-central#724

**Comment by aaclan-ebi** [comment] 2022-04-11 15:23
Also blocked by BioStudies validation :(

**Comment by aaclan-ebi** [comment] 2022-04-11 17:21
There is no need to submit to BioStudies, this is not blocked by BioStudies issue in #724.

**Comment by aaclan-ebi** [comment] 2022-04-13 16:16
The new sequencing runs and the fastq files have been submitted to ENA. They should be available soon in the ENA browser https://www.ebi.ac.uk/ena/browser/view/PRJEB36885?show=reads

The metadata entities for this project have been updated with new sequencing run accessions. The updates need to be submitted to DCP.

**Comment by gabsie** [comment] 2022-04-19 08:51
@ESapenaVentura  - please check this and then move the ticket further

**Comment by ipediez** [comment] 2022-04-22 08:41
The logging credentials were not working yesterday, @ESapenaVentura to try again today as yesterday there were some downtimes on ENA

**Comment by prabh-t** [comment] 2022-04-25 08:44
No new update. ENA downtime on Friday.

**Comment by ke4** [comment] 2022-04-26 08:48
We are going to escalate it with ENA Helpdesk.

**Comment by ofanobilbao** [comment] 2022-04-28 08:39
@ESapenaVentura to reach out to Rasko, as he is the best contact for this

**Comment by Wkt8** [comment] 2022-05-03 08:50
@ESapenaVentura to talk to ENA

**Closed** 2022-05-18 13:27 UTC
Labels: operations
