### ISSUE TITLE
Error when validating Analysis File fields in Ingest production

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#371] opened 2021-06-25 11:53 UTC
**Description of the task:**

When the file source and cell count number fields are filled in a spreadsheet which is uploaded to ingest, including using the example values given (e.g. source is GEO, cell count is an integer), there is an error in ingest production when validating the file. It should validate these fields. This has happened more than 1 once with different datasets where I have included a gene expression matrix file in the Analysis File tab and filled the Analysis Porotcol Tab.
There is also an error when the data normalisation field is filled in the Analysis Protocol Tab.
Example submission in ingest staging: https://staging.contribute.data.humancellatlas.org/submissions/detail?id=60d5c4ef68df001aa684d20d
Protocol error message: "* should NOT have additional properties at .matrix"
File error message: "* should NOT have additional properties at root of document"

**Comment by Wkt8** [comment] 2021-06-28 09:57
The issue is that there were typos in the programmatic name columns of the spreadsheet. 
"analysis_protocol.matrix.data_normalization_method" should be "analysis_protocol.matrix.data_normalization_methods"
"analysis_file.file._core.file_source" should be "analysis_file.file_core.file_source"

This was my error from propagating these errors in the template in the geo_to_hca repo.
I have now updated with a new template, and moved previous templates into an "Outdated Templates" Folder. See here: https://github.com/ebi-ait/geo_to_hca/tree/master/docs

Closing this issue.

**Closed by Wkt8** 2021-06-28 09:57 UTC
Labels: operations
