### ISSUE TITLE
Project Catalogue: Investigate dataset belongs to "Group B"

### ISSUE THREAD

**Issue by ke4** [ebi-ait/hca-ebi-wrangler-central#362] opened 2021-06-16 09:42 UTC

**Comment by ke4** [comment] 2021-06-16 09:45
Te reference sheet: https://docs.google.com/spreadsheets/d/1d3HQLr-nMTlndM9JtM6ZlqiA73M4wk8F1r8aO_krqxA/edit#gid=814662312

Extract from the sheet:
**Target vs Expected**: How many of the target projects are we expecting to be able to add? Are there known categories that might change the target number (e.g. duplicates)

**Expected vs Actual**: How many of the expected projects did we actually add, vs how many we found issues (e.g. duplicates)?

**Comment by Wkt8** [comment] 2021-06-16 09:59
"A single-cell and spatial atlas of autopsy tissues reveals pathology and cellular targets of SARS-CoV-2" in Group D is a preprint and duplicate of the paper

"COVID-19 tissue atlases reveal SARS-CoV-2 pathology and cellular targets"
in Group B

Neither of them are in ingest or the project catalogue. 
I propose setting the Group B 'Covid-19 tissue atlases reveal SARS-CoV-2 pathology and cellular targets' to a hca publication in the dataset tracking sheet, and then deleting the old 'preprint' from Group D.
I can do this quickly - just let me know if you are okay with me doing it. 

Effectively we are deleting something from Group B.

**Comment by ke4** [comment] 2021-06-16 10:03
Thanks @Wkt8.
Just go ahead and do your suggestion. ;-)

**Closed** 2021-06-29 14:12 UTC
Labels: operations
