### ISSUE TITLE
stuck in validating: chronicWoundDiabetes

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#913] opened 2022-09-15 19:02 UTC
*Project Info*
uuid: 34ec845b-cd7a-4c43-99e4-d2932d5d85bb
project short name: chronicWoundDiabetes
primary wrangler: Rachel Schwartz

*background* Several sequence files have been validating for 2 days.
* slack link: 
* email: 

Note:
assign to the current dev on operations.

**Comment by ESapenaVentura** [comment] 2022-09-16 09:01
Duplicate of https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/908, but thanks for creating the ticket!

**Closed by ESapenaVentura** 2022-09-16 09:01 UTC
Labels: operations
