### ISSUE TITLE
phs000424 - Single-nucleus cross-tissue molecular reference maps to decipher disease gene function

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#482] opened 2021-10-06 08:04 UTC
### Project short name: 

CrossTissueReferenceMap

### Primary Wrangler:
Ami

### Secondary Wrangler: 
@ESapenaVentura 

### Associated files

**Google Drive:**
https://docs.google.com/spreadsheets/d/1ZTLK4tU105aa5oTviyOfbaYSwb1xG9WBZ4CgAEse5Wc/edit#gid=1095193694

### Published study links

* Paper: https://doi.org/10.1101/2021.07.19.452954 

* Accessioned data: Raw sequence data are available at AnVIL (https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V9_hg38; dbGaP accession phs000424). Gene expression matrices are available from the GTEx Portal (www.gtexportal.org) and the Single Cell Portal (https://singlecell.broadinstitute.org/single_cell/study/SCP1479/single-nucleus-cross-tissue-molecular-reference-maps).

* HCA Project ID: [dcp7924342437197611](https://contribute.data.humancellatlas.org/projects/detail?uuid=75a9c8d0-50d5-48d9-bff0-462b90330e81)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment] 2021-10-21 14:56
@ami-day I have started secondary review but stopped at specimen from organism.

So far:
Project 
- Added || to separate supplementary links
- Added version to dbGap accession

Donor organism
- Corrected biological sex to match enum
- Corrected ages based on info found on the GTEX biobank. Please review the ones marked in yellow because the age difference was significative, the other ones were 1 year corrections
- All of them have a hardy scale of 0 (ventilator case), but I couldn’t find the cause of death so I couldn’t add the hardy scale.

On the specimen_from_organism issue, I was looking at the column ![image.png](https://images.zenhubusercontent.com/5ca5f897027e3e7234ac788c/ba3979eb-163f-4e37-88c5-00047116693d) from the supplementary table S1, and I compared the values with what there is in the spreadsheet:

|in S1 table|in spreadsheet|
|-------------|---------------|
|GTEX-12BJ1-1226|GTEX-12BJ1-5007|
|GTEX-13N11-0326|GTEX-13N11-5002|
|GTEX-13N11-0426|GTEX-13N11-5030|
|GTEX-144GM-1526|GTEX-144GM-5010|
|GTEX-145ME-0526|GTEX-145ME-5005|
|GTEX-145ME-2026|GTEX-145ME-5018|
|GTEX-15CHR-0726|GTEX-15CHR-5005|
|GTEX-15CHR-1226|GTEX-15CHR-5014|
|GTEX-15EOM-0126|GTEX-15EOM-5003|
|GTEX-15RIE-1726|GTEX-15RIE-5015|
|GTEX-15RIE-2426|GTEX-15RIE-5021|
|GTEX-15SB6-0726|GTEX-15SB6-5008|
|GTEX-16BQI-1526|GTEX-16BQI-5013|
|GTEX-1CAMR-1926|GTEX-1CAMR-5015|
|GTEX-1CAMS-1426|GTEX-1CAMS-5015|
|GTEX-1HSMQ-0726|GTEX-1HSMQ-5005|
|GTEX-1HSMQ-1226|GTEX-1HSMQ-5007|
|GTEX-1HSMQ-1326|GTEX-1HSMQ-5011|
|GTEX-1HSMQ-1826|GTEX-1HSMQ-5014|
|GTEX-1HSMQ-2126|GTEX-1HSMQ-5021|
|GTEX-1I1GU-1126|GTEX-1I1GU-5006|
|GTEX-1ICG6-0626|GTEX-1ICG6-5003|
|GTEX-1ICG6-2026|GTEX-1ICG6-5014|
|GTEX-1MCC2-2126|GTEX-1MCC2-5013|
|GTEX-1R9PN-0326|GTEX-1R9PN-5002|

Where did you get the samples from? I can't find the samples you reference there

**Comment by ESapenaVentura** [comment] 2021-11-09 10:48
Please next time use the existing project entity:
- https://contribute.data.humancellatlas.org/projects/detail?uuid=75a9c8d0-50d5-48d9-bff0-462b90330e81&tab=project (Existing)
- https://contribute.data.humancellatlas.org/projects/detail?uuid=31887183-a72c-4308-9eac-c6140313f39c&tab=project (Exported one)

And remember to fill out the missing overall project fields (Organ, technology, species, etc) so that the catalogue can display them properly.

Another option is to delete the old project and create a new one if you want to use a spreadsheet with the project tabs, but please remember to delete the old one, fill out the fields and click on "submit to project catalogue" so that is shows there.

Other than that, I noticed that this dataset has a shorter project description in the submitted one. Should this be fixed?

**Comment by ESapenaVentura** [comment] 2021-11-09 10:52
Checked the project in the data portal:
- 2 expression matrices (expected)
- Contains a donor with an unspecified organ. Is this expected?

**Comment by ofanobilbao** [comment] 2021-12-07 07:09
@ami-day check comment above, and if expected, please, move this ticket to closed. Thanks!

**Comment by ofanobilbao** [comment] 2021-12-08 15:12
Closing this to clean up the board for the next release. Also the Release was already made live anyway.

**Comment by Wkt8** [comment] 2022-05-24 10:45
Moving to needs update because i'm updating the age ontology terms because cxg uses them and i'm updating the cxg files.

**Comment by Wkt8** [comment] 2022-06-09 08:22
After having a talk with the wranglers we decided not to update the age ontology terms.

**Closed by Wkt8** 2022-06-09 08:22 UTC
Labels: dataset, managed access, hca pub
